# Generated by Django 6.0.5 on 2026-06-02 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0002_apply_business_categories'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='revenuerecord',
            new_name='revenue_rev_date_95b2fa_idx',
            old_name='revenue_rev_date_f_8d2161_idx',
        ),
        migrations.RenameIndex(
            model_name='revenuerecord',
            new_name='revenue_rev_categor_b46cc1_idx',
            old_name='revenue_rev_categor_805c34_idx',
        ),
    ]
